name: reservoir_startuptn
description: "Reservoir management and monitoring system"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  flutter_launcher_icons: ^0.13.1
  iconsax_flutter: ^1.0.0
  get: ^4.6.6
  firebase_core: ^2.25.4
  firebase_auth: 4.15.0
  firebase_messaging: ^14.7.16
  flutter_otp_text_field: ^1.1.1
  mailer: ^6.0.1
  google_fonts: ^6.1.0
  cloud_firestore: ^4.15.5
  google_maps_flutter: ^2.5.3
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  zoom_tap_animation: ^1.1.0
  flex_color_scheme: ^7.3.1
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  intl: 0.18.1
  url_launcher: ^6.2.4
  upi_india: ^3.0.1
  firebase_database: ^10.4.6
  webview_flutter: ^2.2.0
  dotted_border: ^2.1.0
  image_picker: ^1.0.7






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/on_boarding_screen/
    - assets/splash_screen/
    - assets/icons/
    - assets/login_screen/
    - assets/Dataset_sample.csv
    - assets/profile_photo/
    - assets/map_theme/dark_map.json
    - assets/map_theme/water_tank.png
    - assets/gpay_config.json



#  fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
